// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types"
import type * as prismic from "@prismicio/client"

type Simplify<T> = {
	[KeyType in keyof T]: T[KeyType]
}
/** Content for perfil professora literatura tarde documents */
interface AfternoonLiteratureTeacherDocumentData {
	/**
	 * foto_professora field in *perfil professora literatura tarde*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: afternoon_literature_teacher.teacher_img
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	teacher_img: prismicT.ImageField<never>
	/**
	 * nome_professora field in *perfil professora literatura tarde*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: afternoon_literature_teacher.teacher_name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	teacher_name: prismicT.KeyTextField
}
/**
 * perfil professora literatura tarde document from Prismic
 *
 * - **API ID**: `afternoon_literature_teacher`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AfternoonLiteratureTeacherDocument<
	Lang extends string = string
> = prismicT.PrismicDocumentWithUID<
	Simplify<AfternoonLiteratureTeacherDocumentData>,
	"afternoon_literature_teacher",
	Lang
>
/** Content for perfil professora musica tarde documents */
interface AfternoonMusicTeacherProfileDocumentData {
	/**
	 * foto_professora field in *perfil professora musica tarde*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: afternoon_music_teacher_profile.teacher_img
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	teacher_img: prismicT.ImageField<never>
	/**
	 * nome_professora field in *perfil professora musica tarde*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: afternoon_music_teacher_profile.teacher_name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	teacher_name: prismicT.KeyTextField
}
/**
 * perfil professora musica tarde document from Prismic
 *
 * - **API ID**: `afternoon_music_teacher_profile`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AfternoonMusicTeacherProfileDocument<
	Lang extends string = string
> = prismicT.PrismicDocumentWithUID<
	Simplify<AfternoonMusicTeacherProfileDocumentData>,
	"afternoon_music_teacher_profile",
	Lang
>
/** Content for perfil professora literatura manhã documents */
interface MorningLiteratureTeacherDocumentData {
	/**
	 * foto_professora field in *perfil professora literatura manhã*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: morning_literature_teacher.teacher_img
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	teacher_img: prismicT.ImageField<never>
	/**
	 * nome_professora field in *perfil professora literatura manhã*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: morning_literature_teacher.teacher_name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	teacher_name: prismicT.KeyTextField
}
/**
 * perfil professora literatura manhã document from Prismic
 *
 * - **API ID**: `morning_literature_teacher`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MorningLiteratureTeacherDocument<
	Lang extends string = string
> = prismicT.PrismicDocumentWithUID<
	Simplify<MorningLiteratureTeacherDocumentData>,
	"morning_literature_teacher",
	Lang
>
/** Content for perfil professora musica manhã documents */
interface MorningMusicTeacherProfileDocumentData {
	/**
	 * foto_professora field in *perfil professora musica manhã*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: morning_music_teacher_profile.teacher_img
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	teacher_img: prismicT.ImageField<never>
	/**
	 * nome_professora field in *perfil professora musica manhã*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: morning_music_teacher_profile.teacher_name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	teacher_name: prismicT.KeyTextField
}
/**
 * perfil professora musica manhã document from Prismic
 *
 * - **API ID**: `morning_music_teacher_profile`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MorningMusicTeacherProfileDocument<
	Lang extends string = string
> = prismicT.PrismicDocumentWithUID<
	Simplify<MorningMusicTeacherProfileDocumentData>,
	"morning_music_teacher_profile",
	Lang
>
/** Content for posts_professora_literatura_manha documents */
interface PostsProfessoraLiteraturaManhaDocumentData {
	/**
	 * titulo field in *posts_professora_literatura_manha*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: posts_professora_literatura_manha.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	title: prismicT.KeyTextField
	/**
	 * texto field in *posts_professora_literatura_manha*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: posts_professora_literatura_manha.text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	text: prismicT.RichTextField
	/**
	 * imagen_um_post field in *posts_professora_literatura_manha*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: posts_professora_literatura_manha.img_one_post
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	img_one_post: prismicT.ImageField<never>
	/**
	 * imagem_dois_post field in *posts_professora_literatura_manha*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: posts_professora_literatura_manha.img_two_post
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	img_two_post: prismicT.ImageField<never>
	/**
	 * imagen_tres_post field in *posts_professora_literatura_manha*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: posts_professora_literatura_manha.img_three_post
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	img_three_post: prismicT.ImageField<never>
}
/**
 * posts_professora_literatura_manha document from Prismic
 *
 * - **API ID**: `posts_professora_literatura_manha`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostsProfessoraLiteraturaManhaDocument<
	Lang extends string = string
> = prismicT.PrismicDocumentWithUID<
	Simplify<PostsProfessoraLiteraturaManhaDocumentData>,
	"posts_professora_literatura_manha",
	Lang
>
/** Content for posts_professora_literatura_tarde documents */
interface PostsProfessoraLiteraturaTardeDocumentData {
	/**
	 * titulo field in *posts_professora_literatura_tarde*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: posts_professora_literatura_tarde.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	title: prismicT.KeyTextField
	/**
	 * texto field in *posts_professora_literatura_tarde*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: posts_professora_literatura_tarde.text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	text: prismicT.RichTextField
	/**
	 * imagen_um_post field in *posts_professora_literatura_tarde*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: posts_professora_literatura_tarde.img_one_post
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	img_one_post: prismicT.ImageField<never>
	/**
	 * imagem_dois_post field in *posts_professora_literatura_tarde*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: posts_professora_literatura_tarde.img_two_post
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	img_two_post: prismicT.ImageField<never>
	/**
	 * imagen_tres_post field in *posts_professora_literatura_tarde*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: posts_professora_literatura_tarde.img_three_post
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	img_three_post: prismicT.ImageField<never>
}
/**
 * posts_professora_literatura_tarde document from Prismic
 *
 * - **API ID**: `posts_professora_literatura_tarde`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostsProfessoraLiteraturaTardeDocument<
	Lang extends string = string
> = prismicT.PrismicDocumentWithUID<
	Simplify<PostsProfessoraLiteraturaTardeDocumentData>,
	"posts_professora_literatura_tarde",
	Lang
>
/** Content for posts_professora_musica_manha documents */
interface PostsProfessoraMusicaManhaDocumentData {
	/**
	 * titulo field in *posts_professora_musica_manha*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: posts_professora_musica_manha.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	title: prismicT.KeyTextField
	/**
	 * texto field in *posts_professora_musica_manha*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: posts_professora_musica_manha.text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	text: prismicT.RichTextField
	/**
	 * imagen_um_post field in *posts_professora_musica_manha*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: posts_professora_musica_manha.img_one_post
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	img_one_post: prismicT.ImageField<never>
	/**
	 * imagem_dois_post field in *posts_professora_musica_manha*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: posts_professora_musica_manha.img_two_post
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	img_two_post: prismicT.ImageField<never>
	/**
	 * imagen_tres_post field in *posts_professora_musica_manha*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: posts_professora_musica_manha.img_three_post
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	img_three_post: prismicT.ImageField<never>
}
/**
 * posts_professora_musica_manha document from Prismic
 *
 * - **API ID**: `posts_professora_musica_manha`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostsProfessoraMusicaManhaDocument<
	Lang extends string = string
> = prismicT.PrismicDocumentWithUID<
	Simplify<PostsProfessoraMusicaManhaDocumentData>,
	"posts_professora_musica_manha",
	Lang
>
/** Content for posts_professora_musica_tarde documents */
interface PostsProfessoraMusicaTardeDocumentData {
	/**
	 * titulo field in *posts_professora_musica_tarde*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: posts_professora_musica_tarde.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	title: prismicT.KeyTextField
	/**
	 * texto field in *posts_professora_musica_tarde*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: posts_professora_musica_tarde.text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	text: prismicT.RichTextField
	/**
	 * imagen_um_post field in *posts_professora_musica_tarde*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: posts_professora_musica_tarde.img_one_post
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	img_one_post: prismicT.ImageField<never>
	/**
	 * imagem_dois_post field in *posts_professora_musica_tarde*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: posts_professora_musica_tarde.img_two_post
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	img_two_post: prismicT.ImageField<never>
	/**
	 * imagen_tres_post field in *posts_professora_musica_tarde*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: posts_professora_musica_tarde.img_three_post
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	img_three_post: prismicT.ImageField<never>
}
/**
 * posts_professora_musica_tarde document from Prismic
 *
 * - **API ID**: `posts_professora_musica_tarde`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostsProfessoraMusicaTardeDocument<
	Lang extends string = string
> = prismicT.PrismicDocumentWithUID<
	Simplify<PostsProfessoraMusicaTardeDocumentData>,
	"posts_professora_musica_tarde",
	Lang
>
/** Content for projetos documents */
interface ProjectsDocumentData {
	/**
	 * titulo field in *projetos*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	title: prismicT.KeyTextField
	/**
	 * texto field in *projetos*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	text: prismicT.RichTextField
	/**
	 * imagem_um_projeto field in *projetos*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.img_one_project
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	img_one_project: prismicT.ImageField<never>
	/**
	 * imagen_dois_projeto field in *projetos*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.img_two_project
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	img_two_project: prismicT.ImageField<never>
	/**
	 * imagem_tres_projeto field in *projetos*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.img_three_project
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	img_three_project: prismicT.ImageField<never>
	/**
	 * imagen_quatro_projeto field in *projetos*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.img_four_project
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	img_four_project: prismicT.ImageField<never>
}
/**
 * projetos document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> =
	prismicT.PrismicDocumentWithUID<
		Simplify<ProjectsDocumentData>,
		"projects",
		Lang
	>
/** Content for repertorio-musical documents */
interface RepertoireDocumentData {
	/**
	 * video field in *repertorio-musical*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: repertoire.video
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
	 *
	 */
	video: prismicT.LinkField
	/**
	 * letraMusica field in *repertorio-musical*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: repertoire.letramusica
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
	 *
	 */
	letramusica: prismicT.LinkField
	/**
	 * titulo field in *repertorio-musical*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: repertoire.titulo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	titulo: prismicT.KeyTextField
}
/**
 * repertorio-musical document from Prismic
 *
 * - **API ID**: `repertoire`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RepertoireDocument<Lang extends string = string> =
	prismicT.PrismicDocumentWithUID<
		Simplify<RepertoireDocumentData>,
		"repertoire",
		Lang
	>
/** Content for videos documents */
interface VideosDocumentData {
	/**
	 * titulo field in *videos*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: videos.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	title: prismicT.KeyTextField
	/**
	 * data field in *videos*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: videos.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/date
	 *
	 */
	date: prismicT.DateField
	/**
	 * videos field in *videos*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: videos.videos
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
	 *
	 */
	videos: prismicT.LinkField
}
/**
 * videos document from Prismic
 *
 * - **API ID**: `videos`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VideosDocument<Lang extends string = string> =
	prismicT.PrismicDocumentWithUID<
		Simplify<VideosDocumentData>,
		"videos",
		Lang
	>
export type AllDocumentTypes =
	| AfternoonLiteratureTeacherDocument
	| AfternoonMusicTeacherProfileDocument
	| MorningLiteratureTeacherDocument
	| MorningMusicTeacherProfileDocument
	| PostsProfessoraLiteraturaManhaDocument
	| PostsProfessoraLiteraturaTardeDocument
	| PostsProfessoraMusicaManhaDocument
	| PostsProfessoraMusicaTardeDocument
	| ProjectsDocument
	| RepertoireDocument
	| VideosDocument
declare module "@prismicio/client" {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>
	}
	namespace Content {
		export type {
			AfternoonLiteratureTeacherDocumentData,
			AfternoonLiteratureTeacherDocument,
			AfternoonMusicTeacherProfileDocumentData,
			AfternoonMusicTeacherProfileDocument,
			MorningLiteratureTeacherDocumentData,
			MorningLiteratureTeacherDocument,
			MorningMusicTeacherProfileDocumentData,
			MorningMusicTeacherProfileDocument,
			PostsProfessoraLiteraturaManhaDocumentData,
			PostsProfessoraLiteraturaManhaDocument,
			PostsProfessoraLiteraturaTardeDocumentData,
			PostsProfessoraLiteraturaTardeDocument,
			PostsProfessoraMusicaManhaDocumentData,
			PostsProfessoraMusicaManhaDocument,
			PostsProfessoraMusicaTardeDocumentData,
			PostsProfessoraMusicaTardeDocument,
			ProjectsDocumentData,
			ProjectsDocument,
			RepertoireDocumentData,
			RepertoireDocument,
			VideosDocumentData,
			VideosDocument,
			AllDocumentTypes,
		}
	}
}
