import Head from "next/head"
import React from "react"
import { Container, Login, Welcome } from "@/components"

const LoginPage = () => {
	return (
		<Container>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>

				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Login />
			<Welcome />
		</Container>
	)
}

export default LoginPage
